# Welcome to Jekyll!

# Website settings
title: "Vikas Upadhyay"
description: "Vikas Upadhyay profile"
keywords: "Vikas Upadhyay,Vikas Upadhyay Thoughtworks,Vikas Upadhyay Lucknow,Vikas Upadhyay GPL"
baseurl: "/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Vikas Upadhyay'
  first_name: 'Vikas'
  last_name: 'Upadhyay'
  email: 'vikasku@thoughtworks.com'
  facebook_username: 'vikas.upadhyay.984'
  github_username: 'vikashupadhyay'
  avatar: 'static/img/landing/vikas.jpg'
  desc: 'I am Application developer. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: VikasUpadhyay

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
